server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: fcbarca1899
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: http://169.254.0.126:80 # nacos服务地址
#      discovery:
#        cluster-name: HZ
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/

# userservice的ribbon负载均衡
userservice:
  ribbon:
     NFLoadBalanceRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
# ribbon配置
ribbon:
  eager-load:
    enabled: true
    clients:
      - userservice
